version: '3.8'
services:
#  If composer image needs extra libs, copy in docker/composer and use this
#  composer:
#    build:
#      context: ./docker/composer
#      dockerfile: Dockerfile
#    working_dir: /app
#    volumes:
#      - .:/app
#    entrypoint: composer

  composer:
    image: composer
    working_dir: /app
    volumes:
      - .:/app

  tests_unit:
    image: php:7.4-cli
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit
