version: '3.8'
services:

  app_debug:
    build:
      context: .
      dockerfile: Dockerfile-xdebug
    container_name: concr-laravel-app-xdebug
    env_file:
      - ./.env
    volumes:
      - ./:/var/www
    networks:
      - concr-laravel-app-network

  nginx_debug:
    image: nginx:alpine
    ports:
      - '8001:80'
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/xdebug.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/sites:/etc/nginx/sites-available
    networks:
      - concr-laravel-app-network

networks:
  concr-laravel-app-network:
    driver: bridge
